[tool.poetry]
name = "pfun"
version = "0.1.0"
description = ""
authors = ["Sune Debel <sad@archii.ai>"]

[tool.poetry.dependencies]
python = "^3.6"
typing-extensions = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
hypothesis = "^4.32"
mypy = "^0.720.0"
ipython = "^7.7"
ipdb = "^0.12.2"
sphinx = "^2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
