version: 2
jobs:
  build:
    docker:
      - image: jonatkinson/python-poetry:3.7
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "poetry.lock" }}
      - run:
          name: Configure poetry
          command: poetry config settings.virtualenvs.in-project true
      - run:
          name: Install dependencies
          command: poetry install
      - save_cache:
          key: dependency-cache-{{ checksum "poetry.lock" }}
          paths:
            - .venv
      - run:
          name: Lint
          command: poetry run flake8 pfun tests examples
      - run:
          name: Type-check
          command: poetry run mypy pfun tests examples
      - run:
          name: Test
          command: poetry run pytest
